### PR TITLE
Feature/improve arranged search

### PR DESCRIPTION
**Pull request by rudibatt**
This PR would change the default behavior for arranged search: per default all product-sets are now included into main, and only if a product-set declares `"asSeparateSlice": true` it will be separated from `main`.
However facets will still be included in main. @cgicgi  what do you think, should we have extra facets for such a slice as well?

### CODE REVIEW

**Comment by cgicgi** [comment]
Facets should always be included in main-slice - no one will ever display two distinct sets of facets. For me the new approach is fine!

**Review by cgicgi — APPROVED** [review]
LGTM

**Comment by rudibatt** [comment]
Search-Service can be tested with image commerceexperts/ocs-search-service:PR76

**Comment by cgicgi** [comment]
successfully tested. Please merge and release

**Pull request merged**
